language: nodejs
services: "-docker"
stages:
- test
- build
- deploy
git:
  submodules: false
sudo: false
cache:
  directories:
  - public
notifications:
  slack: andi-startup:4EvkZ1UZEV4LwZXzvXhDGP8u
jobs:
  include:
  - stage: test
    name: Test Matching UI component
    script:
    - echo "Testing commit $TRAVIS_COMMIT"
  - stage: build
    name: Build docker matching-ui
    script:
    - echo "Building commit $TRAVIS_COMMIT"
  - stage: deploy
    name: Deploy docker matching-ui
    if: branch = master AND type = push AND fork = false
    script:
    - echo "Deploying commit $TRAVIS_COMMIT"
    # - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker pull berzemus/matching:$TRAVIS_COMMIT
    #   || sleep 5 && true"
    # - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker stop matching || sleep
    #   5 && true"
    # - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker run -d --rm -p 8085:$PORT
    #   --add-host=database:172.17.0.1 --ip 172.17.0.6 -e PROXY_PREFIX=/api -e PG_DSN=$PG_DSN
    #   -e HOST=$HOST -e PORT=$PORT -e LOG_LEVEL=debug --name matching berzemus/matching:$TRAVIS_COMMIT"
addons:
  ssh_known_hosts: andi.beta.gouv.fr
before_install:
- openssl aes-256-cbc -K $encrypted_eaeae9dd8e59_key -iv $encrypted_eaeae9dd8e59_iv
  -in misc/deploy_ed25519.enc -out ./deploy_ed25519 -d
- chmod 600 deploy_ed25519
- echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
- pip install pipenv
